[fix] this should fix the issue that job controller test kept failing
ucsb-cs156-s24/proj-organic-s24-5pm-3 pull request #22
Opened 2024-05-17 04:42 UTC by yuxiaolejs

In this PR, I identified the reason behind the failing CI. Took measures to fix it.

For the whole process of my exploration, please see here: https://github.com/yuxiaolejs/proj-organic-s24-5pm-3/blob/Tianle-Jobs/src/test/java/edu/ucsb/cs156/organic/controllers/JobsControllerTests.java

This should permanently fix the problem.

Closes #21

2024-05-17 04:50 UTC, yuxiaolejs commented
I didn't rerun it for a single time. Everything passed on the first run!

2024-05-17 04:53 UTC, yuxiaolejs commented
More details regarding the bug:

The `jobCaptor` will give a list of all `Job` objects constructed. However, because the tests might run out of order, the first one is not guaranteed to be the one that should fail. What made things worse is that since `jobCaptor` will give a list of `Job`s created previously, it will call the constructor again and again when obtaining the list. Thus, the number of jobs in the list grows exponentially. I didn't address this problem. Instead, I just gave every job an ID, so that we can find the job that should fail when asserting.

2024-05-17 20:10 UTC, pconrad requested changes
Tianle:

Can you add a bit more explanation directly in the PR description of what the logic was behind your approach?

It seems that you added an `id` parameter to the jobs that helps you disambiguate which one is which in the tests.     How does this help avoid the race condition?
Can you explain that a bit?

2024-05-17 20:12 UTC, pconrad commented
> More details regarding the bug:
> 
> The `jobCaptor` will give a list of all `Job` objects constructed. However, because the tests might run out of order, the first one is not guaranteed to be the one that should fail. What made things worse is that since `jobCaptor` will give a list of `Job`s created previously, it will call the constructor again and again when obtaining the list. Thus, the number of jobs in the list grows exponentially. I didn't address this problem. Instead, I just gave every job an ID, so that we can find the job that should fail when asserting.
> 
> @pconrad

@yuxiaolejs This is the kind of explanation I'd like to see on the main page of the PR description. Could you copy/paste it up there, and perhaps also quote some of the code?  I'd like to use this as a way of explaining how to structure code to help avoid the problem of a flaky test.

2024-05-17 22:42 UTC, yuxiaolejs commented
> Tianle:
> 
> Can you add a bit more explanation directly in the PR description of what the logic was behind your approach?
> 
> It seems that you added an `id` parameter to the jobs that helps you disambiguate which one is which in the tests. How does this help avoid the race condition? Can you explain that a bit?

Yes! I have updated it!

2024-05-18 21:09 UTC, Xalex217 reviewed
EDIT: just commented by accident, didn't approve of changes.

2024-05-18 21:13 UTC, Xalex217 approved these changes
Looks good

2024-05-18 21:14 UTC, tmcanepa approved these changes
Looks Good To Me. Makes sense that adding an ID variable would make retrieval after creation more accessible for the test.

2024-05-18 21:19 UTC, pconrad approved these changes
LGTM

2024-05-18 21:20 UTC, merged