CRUD STAFF OPERATION Go to Staff Page from Course Page
ucsb-cs156-s24/proj-organic-s24-5pm-3 pull request #42
Opened 2024-05-24 01:38 UTC by andrew-kwon1

User Story:
I can go to the staff page from the course page

Clicking on staff button on the course page leads to a placeholder staff page. 
![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/assets/92059564/250853b8-37d6-44fd-b66e-d0e91232ea3c)

![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/assets/92059564/12367743-cabb-4b03-a20e-04cc98465f56)

Other members can now wok on other crud operations. 
Closes #37

2024-05-29 02:10 UTC, yuxiaolejs submitted a review, later dismissed
LGTM

2024-05-29 03:29 UTC, pconrad requested changes
Please remove the commented out code, and also fix the branch so it's not tangled up with changes from another PR.

2024-05-29 03:29 UTC, pconrad commented on frontend/src/main/pages/CoursesStaffPage.js
> +//import { useBackend } from "main/utils/useBackend";
Please remove commented out code

2024-05-29 03:29 UTC, pconrad commented on src/main/resources/application-development.properties
> +spring.h2.console.enabled=${H2_CONSOLE_ENABLED:${env.H2_CONSOLE_ENABLED:true}}
Why is this in this branch?

2024-05-29 03:29 UTC, pconrad commented on src/main/resources/application-production.properties
> +spring.h2.console.enabled=${H2_CONSOLE_ENABLED:${env.H2_CONSOLE_ENABLED:false}}
This should not be in this branch.

2024-05-29 03:29 UTC, pconrad commented on src/main/resources/application-development.properties
> +spring.h2.console.enabled=${H2_CONSOLE_ENABLED:${env.H2_CONSOLE_ENABLED:true}}
Please remove this from this branch.

2024-05-30 00:28 UTC, andrew-kwon1 commented on frontend/src/main/pages/CoursesStaffPage.js
> +//import { useBackend } from "main/utils/useBackend";
Removed

2024-05-30 00:28 UTC, andrew-kwon1 commented on src/main/resources/application-development.properties
> +spring.h2.console.enabled=${H2_CONSOLE_ENABLED:${env.H2_CONSOLE_ENABLED:true}}
Removed

2024-05-30 00:28 UTC, andrew-kwon1 commented on src/main/resources/application-production.properties
> +spring.h2.console.enabled=${H2_CONSOLE_ENABLED:${env.H2_CONSOLE_ENABLED:false}}
Removed

2024-05-30 18:03 UTC, pconrad submitted a review, later dismissed
LGTM

2024-05-30 18:03 UTC, merged