[merge] combined package com.tianleyu.com
ucsb-cs156-s24/proj-organic-s24-5pm-3 pull request #46
Opened 2024-05-27 21:43 UTC by yuxiaolejs

This gives errors on Mockito, anyone has any idea about it?

2024-05-31 00:40 UTC, 30912hyl reviewed
that's a lot of changed files...would it be better/possible to split this into smaller PRs?

2024-05-31 00:49 UTC, yuxiaolejs commented
> that's a lot of changed files...would it be better/possible to split this into smaller PRs?

Not really... They are dependent on each other

2024-05-31 00:54 UTC, 30912hyl commented
LGTM

2024-05-31 00:56 UTC, 30912hyl submitted a review, later dismissed
LGTM

2024-05-31 23:29 UTC, pconrad commented on README.md
> +| qa   | <https://organic-qa.dokku-11.cs.ucsb.edu/>  |
Please revert this.  This is intended as documentation of the production links.

2024-05-31 23:31 UTC, pconrad commented on frontend/src/tests/pages/CoursesJoinPage.test.js
> +            // const restoreConsole = mockConsole();
commented out code.

2024-05-31 23:31 UTC, pconrad commented on frontend/src/tests/pages/CoursesJoinPage.test.js
> +            // restoreConsole();
commented out code

2024-05-31 23:31 UTC, pconrad commented on frontend/src/tests/pages/CoursesJoinPage.test.js
> +            // const restoreConsole = mockConsole();
commented out code

2024-05-31 23:31 UTC, pconrad commented on frontend/src/tests/pages/CoursesJoinPage.test.js
> +            // const restoreConsole = mockConsole();
commented out code

2024-05-31 23:32 UTC, pconrad commented on frontend/src/tests/pages/CoursesJoinPage.test.js
> +            // restoreConsole();
commented out code

2024-06-01 00:00 UTC, pconrad requested changes
There are some commented out lines of code.

Please fix these; then the code looks good.  I will experiment with it on my own dokku deployment, and see if we can get it to a mergeable state.

This is really solid good work, and will earn extra credit points for the team. I'm hopeful, though that the team can get to 100 points without it :-)

2024-06-06 23:11 UTC, closed without merging