Linked API to Create School button, added tests and Storybook
ucsb-cs156-s24/proj-organic-s24-5pm-3 pull request #57
Opened 2024-05-30 00:02 UTC by sherpatran

Made sure that the CreateSchool button is working. Connected it to the proper Schools POST api and added the tests/storybook for that feature.

https://organic-sherpatran-dev.dokku-11.cs.ucsb.edu/

Closes #7 and closes #8.

2024-05-30 21:52 UTC, pconrad requested changes
Several things that need to be fixed...

2024-05-30 21:52 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptor.java
> +package edu.ucsb.cs156.organic.Interceptors;
NOOOOO!!! 

We already fixed this!
Don't bring back this bad code that is unrelated to your changes!

2024-05-30 21:52 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorAppConfig.java
> +package edu.ucsb.cs156.organic.Interceptors;
NOOOOO!!! 

We already fixed this!
Don't bring back this bad code that is unrelated to your changes!

2024-05-30 21:52 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
> +package edu.ucsb.cs156.organic.Interceptors;
NOOOOO!!! 

We already fixed this!
Don't bring back this bad code that is unrelated to your changes!

2024-05-30 21:52 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
> +        String decodedTermRegex = URLDecoder.decode(termRegex, StandardCharsets.UTF_8);
This should be discussed in the PR description.

2024-05-31 01:37 UTC, 30912hyl requested changes
Can you add me as admin for testing dev deployment?

2024-06-01 00:05 UTC, pconrad submitted a review, later dismissed
<img width="685" alt="image" src="https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/assets/1119017/9af728fd-af7c-4d85-877b-ee5dfcee9046">

2024-06-01 18:12 UTC, pconrad requested changes
Why are there changes to backend files in this PR?

It makes this harder to review.  Including changes to files that are unrelated to the PR is frowned upon in professional SW dev.

This page explains how you can easily remove the changes to some files from your PR:

https://ucsb-cs156.github.io/topics/pull_requests/pull_requests_simplifying.html

2024-06-01 18:44 UTC, sherpatran commented
> Why are there changes to backend files in this PR?
> 
> It makes this harder to review. Including changes to files that are unrelated to the PR is frowned upon in professional SW dev.
> 
> This page explains how you can easily remove the changes to some files from your PR:
> 
> https://ucsb-cs156.github.io/topics/pull_requests/pull_requests_simplifying.html

The changes to the backend were necessary because of the encoding issues with TermRegex. I also believe that I removed the changes to the interceptor. Should I still break up this PR into the changes to frontend and backend?

2024-06-02 18:06 UTC, closed without merging

2024-06-02 18:07 UTC, sherpatran commented
Created new PR with cleaner commits.