[merge] Feature: add a single student to the course API
ucsb-cs156-s24/proj-organic-s24-5pm-3 pull request #68
Opened 2024-05-31 09:27 UTC by yuxiaolejs

More details later

2024-05-31 23:11 UTC, pconrad requested changes
One commented out line, otherwise LGTM

2024-05-31 23:11 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/controllers/StudentsController.java
> +    // @PreAuthorize("hasRole('ROLE_ADMIN')")
Commented out code...

2024-05-31 23:14 UTC, sherpatran submitted a review, later dismissed
LGTM besides the commented line

2024-05-31 23:30 UTC, yuxiaolejs commented on src/main/java/edu/ucsb/cs156/organic/controllers/StudentsController.java
> +    // @PreAuthorize("hasRole('ROLE_ADMIN')")
Removed!

2024-06-01 00:18 UTC, tmcanepa approved these changes
LGTM

2024-06-01 19:18 UTC, pconrad approved these changes
LGTM

2024-06-01 19:18 UTC, merged